# file: root_rotate.yml
---
- hosts: database
  tasks:
    
    - name: retrieve keys locally
      set_fact:
        vault_keys: "{{ lookup('file','~/.hashicorp_vault_keys.json') | from_json }}"
      delegate_to: localhost
      become: no
    
    - name: read mysql secret to vault
      uri:
        url: "https://vault.ansiblefest.com:8201/v1/secret/AnsibleFest/database"
        headers:
          X-Vault-Token: "{{ vault_keys.root_token }}"
      delegate_to: localhost
      become: no
      register: vault_secret

    - name: generate 20-char random password string
      shell: </dev/urandom tr -dc '1234567890qwertyuiop' | head -c20; echo
      register: rand_pw_string
      delegate_to: localhost
      become: no
      
    - name: write mysql secret to vault
      uri:
        url: "https://vault.ansiblefest.com:8201/v1/secret/AnsibleFest/database"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_keys.root_token }}"
        body:
          mysqlrootpw: "{{ rand_pw_string.stdout }}"
        body_format: json
        status_code: 204
      delegate_to: localhost
      become: no
  
    - name: set initial root password
      mysql_user:
        name: root
        password: "{{ rand_pw_string.stdout }}"
        host: localhost
        state: present
        login_host: localhost
        login_user: root
        login_password: "{{ vault_secret.json.data.mysqlrootpw }}"
      delegate_to: database
