---
# tasks file for roles/httpd

- name: install webserver rpms
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - php
    - php-mysql

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
